# Generated by Django 2.1.3 on 2018-12-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('phone', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Numer telefonu')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Szerokość')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Długość')),
                ('message', models.TextField(verbose_name='Wiadomość')),
                ('picture', models.TextField(verbose_name='Zdjęcie(base64)')),
            ],
            options={
                'verbose_name': 'Marker',
                'verbose_name_plural': 'Markery',
                'ordering': ('created',),
            },
        ),
    ]
